import type { Plan, SaasUser, AuditLogEntry } from './types';

const now = () => new Date().toISOString();

export const SEED_PLANS: Plan[] = [
  {
    id: 'plan_free',
    name: 'Free',
    slug: 'free',
    description: 'Get started with core order management. Perfect for trying the platform.',
    priceMonthly: 0,
    priceYearly: 0,
    currency: 'USD',
    features: {
      maxOrdersPerMonth: 50,
      inventory: false,
      courierIntegrations: false,
      aiOrderParsing: true,
      analytics: false,
      teamMembers: 1,
      prioritySupport: false,
      customBranding: false,
    },
    isActive: true,
    isDefault: true,
    sortOrder: 1,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'plan_pro',
    name: 'Pro',
    slug: 'pro',
    description: 'Unlimited orders, inventory, courier APIs, and advanced tools for growing shops.',
    priceMonthly: 29,
    priceYearly: 290,
    currency: 'USD',
    features: {
      maxOrdersPerMonth: -1,
      inventory: true,
      courierIntegrations: true,
      aiOrderParsing: true,
      analytics: true,
      teamMembers: 5,
      prioritySupport: true,
      customBranding: true,
    },
    isActive: true,
    isDefault: false,
    sortOrder: 2,
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'plan_business',
    name: 'Business',
    slug: 'business',
    description: 'For agencies and multi-store operators who need higher limits and support.',
    priceMonthly: 79,
    priceYearly: 790,
    currency: 'USD',
    features: {
      maxOrdersPerMonth: -1,
      inventory: true,
      courierIntegrations: true,
      aiOrderParsing: true,
      analytics: true,
      teamMembers: 25,
      prioritySupport: true,
      customBranding: true,
    },
    isActive: true,
    isDefault: false,
    sortOrder: 3,
    createdAt: now(),
    updatedAt: now(),
  },
];

export const SEED_USERS: SaasUser[] = [
  {
    id: 'user_super',
    email: 'super@admin.com',
    name: 'Super Admin',
    role: 'super_admin',
    planId: 'plan_business',
    status: 'active',
    company: 'Platform HQ',
    phone: '+8801700000001',
    ordersUsedThisMonth: 0,
    createdAt: now(),
    updatedAt: now(),
    lastLoginAt: now(),
  },
  {
    id: 'user_admin',
    email: 'admin@demo.com',
    name: 'Demo Admin',
    role: 'admin',
    planId: 'plan_pro',
    status: 'active',
    company: 'Ops Team',
    phone: '+8801700000002',
    ordersUsedThisMonth: 12,
    createdAt: now(),
    updatedAt: now(),
    lastLoginAt: now(),
  },
  {
    id: 'user_pro',
    email: 'pro@demo.com',
    name: 'Pro Shop Owner',
    role: 'pro',
    planId: 'plan_pro',
    status: 'active',
    company: 'Rifa Baby Shop',
    phone: '+8801700000003',
    ordersUsedThisMonth: 128,
    createdAt: now(),
    updatedAt: now(),
    lastLoginAt: now(),
  },
  {
    id: 'user_free',
    email: 'free@demo.com',
    name: 'Free Shop Owner',
    role: 'free',
    planId: 'plan_free',
    status: 'active',
    company: 'Starter Store',
    phone: '+8801700000004',
    ordersUsedThisMonth: 18,
    createdAt: now(),
    updatedAt: now(),
    lastLoginAt: now(),
  },
  {
    id: 'user_team_pro',
    email: 'staff@rifa.com',
    name: 'Rifa Staff',
    role: 'team_member',
    planId: 'plan_pro',
    status: 'active',
    company: 'Rifa Baby Shop',
    ownerId: 'user_pro',
    permissions: {
      dashboard: true,
      createOrders: true,
      onHold: true,
      courierAssign: true,
      shipping: true,
      delivered: true,
      inventory: false,
      customers: true,
      search: true,
      settings: false,
      manageTeam: false,
    },
    ordersUsedThisMonth: 0,
    createdAt: now(),
    updatedAt: now(),
    lastLoginAt: now(),
  },
];

export const SEED_AUDIT: AuditLogEntry[] = [
  {
    id: 'audit_1',
    actorId: 'user_super',
    actorName: 'Super Admin',
    action: 'Seeded platform plans and demo accounts',
    createdAt: now(),
  },
  {
    id: 'audit_2',
    actorId: 'user_pro',
    actorName: 'Pro Shop Owner',
    action: 'Added team member',
    target: 'staff@rifa.com',
    createdAt: now(),
  },
];
